### ISSUE TITLE
JPEG format is not available on GraphViz

### ISSUE THREAD

**Issue by pambrose** [yuzutech/kroki#1336]
If I issue: `https https://kroki.io/graphviz/svg/eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSanlAgB1EAjQ`
I get the proper svg response.

 If I issue: `https https://kroki.io/graphviz/jpg/eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSanlAgB1EAjQ`
I get: 
`Error 400: Unsupported output format: jpg. Must be one of graphviz for png, svg or jpeg.`

If I issue: `https https://kroki.io/graphviz/jpeg/eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSanlAgB1EAjQ`
I get: 
`Error 500: Format: "jpeg" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gv imap imap_np ismap json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tk vdx vml vmlz x11 xdot xdot1.2 xdot1.4 xdot_json xlib
 (exit code 1)`
 
So, it seems there is a problem with GraphViz and the jpeg output format. 

Thanks,
Paul

**Comment by Mogztter** [comment]
I thought that the jpeg output format was available by default in the [graphviz Alpine package](https://pkgs.alpinelinux.org/package/v3.16/main/x86_64/graphviz) but apparently that's not the case.

Upstream issue: https://gitlab.alpinelinux.org/alpine/aports/-/issues/14199

The error message is also incorrect, it should read:

```
Error 400 Unsupported output format: jpg for graphviz. Must be one of png, svg or jpeg.
```

In the meantime, I will remove this format since it's not actually available.

**Comment by pambrose** [comment]
Excellent. Thanks for the quick response. 

I greatly appreciate your efforts with this project.

**Comment by Mogztter** [comment]
We can keep this issue open until it's "resolved".

> I greatly appreciate your efforts with this project.

Thanks 😊

**Comment by Mogztter** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/14199 was fixed and I believe that the JPEG output is available on Alpine 3.16. I will give it a try.

**Comment by pambrose** [comment]
I am still getting the same error msg, but I assume that is because you have not switched your site over to 3.16.

**Comment by Mogztter** [comment]
Yes that's correct, I plan to upgrade all images to Alpine 3.16 for the next version.

**Comment by Mogztter** [comment]
> The error message is also incorrect, it should read:

it's actually already fixed in: https://github.com/yuzutech/kroki/pull/1296 (available in the next release)

**Comment by Mogztter** [comment]
Actually, the jpeg output is only available on Alpine "edge" 3.17 so it won't be available in the next release of Kroki (unless this feature is backport to the 3.16 branch: https://gitlab.alpinelinux.org/alpine/aports/-/issues/14199#note_273532

**Comment by Mogztter** [comment]
Fixed in 0.18.0

https://kroki.io/graphviz/jpeg/eNp9kM0KgzAQhO8-xZIHaKlX6Ulp6S-FPoDEuGhqbML6cyl594JVGyv1OMPMt8ukMiNucojg5QFUTfKRQjVVjRSbzgZQPEEFW2An0oVkQWfO0mLTx53CHalF6hsAO6kwQV4PesbIRPylOJxIiwJp_YMDOPKWD8ouQP0F6AWp5DJ1qOyqU1w9Kte6NcZgjZPrLMxJl8imH9g_8_jzecLzYSzvteLPLBgR1rNvJ7Rwmw==
