### ISSUE TITLE
GPU process launch failed on mermaid container

### ISSUE THREAD

**Issue by mariotoffia** [yuzutech/kroki#1400]
Hi and thanks for your fantastic project!

I've stumbled into two problems (the other I've added to another already open thread).

My environment is a Mac M1 (arm64) and `0.18.0` for the containers. The version `0.17.2` works like a charm! :)

It get lots of errors on the mermaid container, I've googled it and found an interesting answer on [stack overflow](https://stackoverflow.com/a/73295941) that seems to fix the problem (this is way over my league).

The problem log:

```shell
qemu: unknown option 'type=utility'
kroki-mermaid-1      | [1202/054624.912567:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
kroki-mermaid-1      | [1202/054624.915318:ERROR:gpu_process_host.cc(967)] GPU process launch failed: error_code=1002
kroki-mermaid-1      | [1202/054624.916075:WARNING:gpu_process_host.cc(1273)] The GPU process has crashed 1 time(s)
kroki-mermaid-1      | [1202/054625.141590:ERROR:gpu_process_host.cc(967)] GPU process launch failed: error_code=1002
kroki-mermaid-1      | [1202/054625.141657:WARNING:gpu_process_host.cc(1273)] The GPU process has crashed 2 time(s)
kroki-mermaid-1      | [1202/054625.148070:ERROR:network_service_instance_impl.cc(470)] Network service crashed, restarting service.
kroki-mermaid-1      | qemu: unknown option 'type=utility'
kroki-mermaid-1      | [1202/054625.188976:ERROR:gpu_process_host.cc(967)] GPU process launch failed: error_code=1002
kroki-mermaid-1      | [1202/054625.191424:WARNING:gpu_process_host.cc(1273)] The GPU process has crashed 3 time(s)
```

Cheers,
 Mario :)

**Comment by Mogztter** [comment]
We might need to add additional flags when we launch Chromium. I don't have a Mac M1 (arm64) at hand, would you be able to build and test an image locally?

**Comment by mariotoffia** [comment]
I'll gladly do that - how do I do that?

**Comment by Mogztter** [comment]
I will push a branch with a fix, then you will need to:

- clone the repository (my fork)
- checkout a branch that contains the fix
- build the image locally on arm64 using `docker buildx` and `docker bake`
- run the container on arm64 to make sure that the issue is fixed

I will let you know when the branch is ready.

**Comment by Mogztter** [comment]
@mariotoffia could you please checkout https://github.com/Mogztter/kroki/tree/chromium-arm64 branch and run `docker buildx bake --set "*.platform=linux/arm64" --set="*.output=type=docker" kroki-mermaid` ?

Then, you should be able to run `docker run yuzutech/kroki-mermaid:latest`.

Thanks!

**Comment by Mogztter** [comment]
Let me know if it's working, we might need to add `--no-zygote` in:

https://github.com/Mogztter/kroki/blob/ddf91af290b89e786d8e7a5c680aab6cd1a461dd/mermaid/src/browser-instance.js#L9

> Disables the use of a zygote process for forking child processes. Instead, child processes will be forked and exec'd directly. Note that --no-sandbox should also be used together with this flag because the sandbox needs the zygote to work. https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/content_switches.cc?q=kNoZygote&ss=chromium

https://peter.sh/experiments/chromium-command-line-switches/

**Comment by mariotoffia** [comment]
Hi and thanks @Mogztter  (and sorry for being so late)...

I get a problem when trying to invoke the docker command
`docker buildx bake --set "*.platform=linux/arm64" --set="*.output=type=docker" kroki-mermaid` and I don't know how to fix it - sorry :(

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/1716527/208253605-36c6ba37-1c7a-4ff6-8a76-ebc697742875.png">

**Comment by mariotoffia** [comment]
@Mogztter  works like a charm - now I can render using mermaid!!

Thanks!! :)

**Comment by Mogztter** [comment]
Thanks for checking, I will include this change and release a version later this month

**Comment by FelixVanOost** [comment]
@ggrossetie I think this should be resolved now with all the changes since December?

**Comment by ggrossetie** [comment]
Yes you're right. We still have issues with Mermaid though but (I believe) it's unrelated.
